### ISSUE TITLE
Drop down menus open 

### ISSUE THREAD

**Issue by TacTicToe66** [Prosk8er/phpBB3-Styles#2]
I updated to 3.2 and for some reason the drop down menus are all open and wont close.  

http://www.gameservertrack.com/forum

Style: proDVGFX 

Seems to have affected all of your styles though.

**Comment by Prosk8er** [comment]
the styles havent been updated yet they’ll only work on 3.1.x

From: TacTicToe66 
Sent: Wednesday, January 11, 2017 3:26 AM
To: Prosk8er/phpBB3-Styles 
Cc: Subscribed 
Subject: [Prosk8er/phpBB3-Styles] Drop down menus open (#2)

I updated to 3.2 and for some reason the drop down menus are all open and wont close.

http://www.gameservertrack.com/forum

Style: proDVGFX

Seems to have affected all of your styles though.

**Comment by TacTicToe66** [comment]
Kind of my point I guess. I would not have updated by board if I had realized this sooner. Do you intend to update this style?

**Comment by TacTicToe66** [comment]
Harro?!

Are you planning to update and fix this or should I just look for 
another style?

thanks

**Comment by Prosk8er** [comment]
when I have some time it will get updated

**Comment by TacTicToe66** [comment]
Been a year now. Anything???

**Comment by Prosk8er** [comment]
nope haven't had any time to mess with phpbb
